### ISSUE TITLE
design and discuss command line interface 

### ISSUE THREAD

**Issue by cgcostume** [cginternals/openll-asset-generator#4]
This issue should be used to identify constraints and requirements and subsequently to derive and discuss the command line interface of llassetgen before implementing one.

**Comment by cgcostume** [comment]
I suggest to assume an the executable to be named `llag` or `llassetgen`. We should not abbreviate _font asset generator_ and focus on _label library_ instead of _font_ to avoid inconvenient identifier.

**Comment by cgcostume** [comment]
Please discuss here if and why [cppassist/cmdline](https://github.com/cginternals/cppassist) should be used as basis for parsing arguments.

**Comment by cgcostume** [comment]
how can we communicate progress when computing/baking such as _time remaining_ or _ascii progress bar_ or similar. Also, i would expect some kind of verbose summary of the quality and file size properties for all created assets.

**Comment by cgcostume** [comment]
Since the cli application will presumably link the llassetgen lib, a robust and documented error handling should be implemented.

**Comment by anne-gropler** [comment]
@Blaidd-Drwg Is there any update of this issue? Is there work in progress, is it stale, or is it done?

**Comment by Blaidd-Drwg** [comment]
Stale, I'd say.  All progress on the CLI has been merged into master, but some of Daniel's suggestions are still missing. To address his comments:
- We do not use the cppassist library, we decided on [CLI11](https://github.com/CLIUtils/CLI11) instead.
- There is no progress indicator nor a verbose option as of yet.
- Error handling would need to be addressed in the library first and foremost, since calls to `abort` hardly qualify as "robust and documented".
